-- This configuration file was auto-generated by waywall. Refer to the
-- documentation for more information on how to configure waywall!
--
-- To remove the auto-generated notice, delete the 'config.autogen = true'
-- line at the bottom of the file.

local waywall = require("waywall")
local helpers = require("waywall.helpers")

local config = {
    theme = {
        background = "#303030ff",
    },
}

config.actions = {}

config.autogen = true -- Delete me to remove the auto-generated notice

return config
